### PR TITLE
fix: handle 401 response parsing correctly in userInfo endpoint

### LINKED ISSUE #1375: /userinfo response is broken with status 401
### Checklist

- [ ] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [x] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [x] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi team,
we are encountering an issue with the `/userInfo` API with the latest `v5.0.1`.
When the `token is expired` the status code `401` is correct but the response is broken and this causes a general `NetworkError`. This error blocks the process to refresh the token because the 'invalid grant' is not returned from the API body.

Could you please give a check?

Below some examples of the error taken from Reactotron:
Broken /userinfo API response

Image

And the console.log error:

Image

This is the point in your library where the exception is thrown:

Image

### Reproduction

1. invoke `auth0.auth.userInfo({token})` when the token is expired
2. the API returns a status code 401
3. when the response is parsed it throws a NetworkError and not an 'invalid_token' message

### Additional context

_No response_

### react-native-auth0 version

v5.0.1

### React Native version

0.81.5

### Expo version

_No response_

### Platform

Android

### Platform version(s)

16

### PR DESCRIPTION
**Pull request by subhankarmaiti**
When the `/userinfo` endpoint returns a 401 status code (expired token), the SDK throws a `NetworkError` instead of a proper `AuthError` with the error details (like `invalid_token`).

Fixes #1375

### CODE REVIEW

File: src/core/services/HttpClient.ts [hunk 1]
```diff
@@ -96,12 +96,14 @@ export class HttpClient {
...
+        // Read text first to avoid body-already-consumed errors when JSON parsing fails
+        const text = await response.text();
         try {
-          json = await response.json();
+          json = JSON.parse(text);
         } catch {
           json = {
             error: 'invalid_json',
-            error_description: await response.text(),
+            error_description: text,
```
Comment (sanchitmehtagit) [inline src/core/services/HttpClient.ts]: nit:  we could wrap this to  a func async function safeJson(response: Response) {}

**Review by sanchitmehta94 — DISMISSED** [review]
LGTM

**Review by sanchitmehta94 — APPROVED** [review]
Thank you. LGTM
