### PR TITLE
fix(docs): organize exports into namespaces for better typedocs

### LINKED ISSUE #1267: Internal doc pages not available
### Checklist

- [x] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [x] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [x] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When accessing the react-native-auth0 docs at https://auth0.github.io/react-native-auth0/, a number of links 404 when clicked. Specifically the ones listed under `<internal>` in the sidebar. I know these used to be accessible in the past because the most common one I referenced was `Auth0ContextInterface`, the return type of `useAuth()`. But that page now 404s as well: https://auth0.github.io/react-native-auth0/interfaces/_internal_.Auth0ContextInterface.html

I am actually still using 5.0.0-beta.3 and would prefer to access docs for that version, but I can't see any way to access previous version docs. This is unfortunate because beta 4 is not recommended for production use, so now we don't have access to docs for a recommended production version.

### Reproduction

- Go to https://auth0.github.io/react-native-auth0/modules.html
- Click any link listed under `<internal>` on the right

### Additional context

_No response_

### react-native-auth0 version

5.0.0-beta.4

### React Native version

n/a

### Expo version

_No response_

### Platform

iOS, Android

### Platform version(s)

n/a

### PR DESCRIPTION
**Pull request by subhankarmaiti**
This PR introduces a major overhaul of our documentation generation and publishing process, aimed at improving navigation, clarity, and maintainability.

### 1. Improved Documentation Structure

The library's exports have been restructured to create a clear, hierarchical structure in the generated TypeDoc documentation. Previously, the docs presented a flat list of all exports, making them difficult to navigate. Now, all public types, classes, and functions are organized into distinct namespaces:

*   **`Classes`**: Contains all exported classes like `Auth0`, `AuthError`, etc.
*   **`Interface`**: Contains all TypeScript interfaces and type aliases.
*   **`Hooks`**: Contains the React hooks, `useAuth0` and `Auth0Provider`.
*   **`Enums`**: Contains all enums like `LocalAuthenticationStrategy`.

This creates a much clearer experience for developers browsing the API documentation.

### 2. Automated Publishing and Versioning

To support this new structure and streamline our release process, a full CI/CD pipeline for the documentation has been implemented:

*   A new **`publish-docs` GitHub Actions workflow** now automatically builds and commits the documentation to the `gh-pages` branch after each release.
*   A **version management script** and a new **TypeDoc versioning plugin** have been added. This system automatically maintains documentation for the two most recent major versions, providing users with a version selector in the docs.
*   As a result, the `docs` directory is now treated as a build artifact and has been added to `.gitignore`.

These changes make the documentation significantly easier for developers to use while automating a previously manual part of our release workflow.

Fixes #1267

### CODE REVIEW

**Review by pmathew92 — DISMISSED** [review]

File: scripts/manage-doc-versions.js [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+    semver.rcompare
+  );
+  const isCurrentPrerelease = semver.prerelease(currentVersion);
+
+  if (isCurrentPrerelease) {
+    // Scenario B: Pre-release - Keep latest stable major + current pre-release major
+    const currentMajor = semver.major(currentVersion);
+    const stableVersions = allVersions.filter((v) => !semver.prerelease(v));
+    const latestStableMajor = stableVersions.find(
+      (v) => semver.major(v) < currentMajor
```
Comment (nandan-bhat) [inline scripts/manage-doc-versions.js:56]: What will happen when you cut a `-beta` release on the latest stable version.
`latestStableMajor = 4` and `currentVersion = `4.3.5-beta.1`

**Review by nandan-bhat — APPROVED** [review]

File: scripts/manage-doc-versions.js (hunk 1 above)
Comment (subhankarmaiti) [reply scripts/manage-doc-versions.js:56]: In that case, it will only keep the `4.3.5-beta.1` version.
Should we account for this scenario? I was under the assumption that we release beta or alpha versions only for the next major release. Please correct me if that’s not the case, so we can adjust to keep both versions if needed.
